# Generated by Django 4.0.5 on 2022-11-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default='maaz', max_length=50),
            preserve_default=False,
        ),
    ]
